### ISSUE TITLE
Running the latest versions patrol 2.3.0 and patrol_cli 2.2.0 fails to build the tests. kotlinx.serialization.SerializationException: Serializer for class 'ListDartTestsResponse' is not found.

### ISSUE THREAD

**Issue by adrian-moisa** [leancodepl/patrol#1793]
### Steps to reproduce

Install patrol 2.3.0 and patrol_cli 2.2.0 according to official specs (these are the latest currently available versions). https://patrol.leancode.co/getting-started.

android/build.gradle:
ext.kotlin_version = '1.9.0'

Running on a mac m1.

I tried 2 different emulator devices, both have the same issue.

### Actual results

When running `patrol test -t integration_test/example_test.dart --verbose` I get the following error:

`Failed to execute tests of apk with entrypoint test_bundle.dart. Exception: Gradle test execution failed with code 1` - There's little to no useful info in this error message even with verbose.

I used logcat and found the following underlying issue.

`kotlinx.serialization.SerializationException: Serializer for class 'ListDartTestsResponse' is not found. Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.`

I tried installing in gradle this plugin following the official instructions: https://github.com/Kotlin/kotlinx.serialization#using-the-plugins-block

```

		plugins {
			id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.0'
		}
		repositories {
			mavenCentral() // Already defined in android/build.gradle
		}

		dependencies {
			implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"
		}
```

Had no luck. Eventually I tried a last ditch effort to revert back to an earlier version of patrol. 

	- patrol: 2.2.5 (instead of 2.3.0)
	- dart pub global activate patrol_cli 2.1.5 (instead of 2.2.0)
	
It worked

### Logs

<details>
<summary>Logs</summary>

```
By the time I found the fixed I had not access to the old logs.
I tried to rever back to the versions I initially tried. 
This time the bug no longer shows.  However, this time the terminal hangs at and never closes:

: > Task :app:connectedDebugAndroidTest

I no longer see the serializer error in logcat. By the looks of it this is going to be tricky to reproduce.
```

</details>

### Patrol version

patrol 2.3.0 and patrol_cli 2.2.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME set to ~/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.4 22F66 darwin-arm64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
Hi @adrian-moisa, sorry for the problem. [It's a known bug](https://github.com/leancodepl/patrol/issues/1775) that has been fixed on [the latest dev version](https://pub.dev/packages/patrol/versions/2.4.0-dev.2).

**Comment by bartekpacia** [comment]
Please try using latest patrol `v2.3.1`.

**Comment by adrian-moisa** [comment]
Oh boy, I was quite lucky to get my first patrol setup running on 2.3.0 :) It really tested my determination to use it. However, after seeing the quality of your docs I figured that this is only a temporary thing. Also any version that ends in .0 can be full of surprises. I'll try 2.3.1 and report back. I'm quite sure it will be fine. I'm stuck on some other issue now (trying to get keycloak to run on the mobile build, started from the web).

**Comment by bartekpacia** [comment]
Yeah, sorry about that – we didn't foresee that using kotlinx.serialization could have so bad consequences.

Thanks for sticking around, I hope it'll only get better from now on :)

**Comment by lockieRichter** [comment]
I'm still having issues on version `v2.3.1`.

When I run `patrol test` with an android emulator running  and the example test from the docs I get the following output.

```
warning: [options] source value 8 is obsolete and will be removed in a future release
        warning: [options] target value 8 is obsolete and will be removed in a future release
        warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
        error: warnings found and -Werror specified

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':audio_session:compileDebugJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 5s
        : 
        : Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```

I'm using `patrol_cli v2.2.1`, `patrol doctor` isn't reporting any issues and I have tried a `flutter clean` and a `dart pub cache repair`, no dice

**Comment by bartekpacia** [comment]
@lockieRichter this issue looks unrelated to Patrol. I googled it and [found this](https://stackoverflow.com/questions/64791058/warning-options-source-value-7-is-obsolete-and-will-be-removed-in-a-future-re), please see if it helps you.

**Comment by lockieRichter** [comment]
hmm possibly, I am running a newer version of Java, but I don't have any issues building the app though the command line for Android 🤔

**Comment by lockieRichter** [comment]
Ok I downgraded my Java version to 17 and everything seems to be working again, thanks @bartekpacia!
