### ISSUE TITLE
Can't run test in Android

### ISSUE THREAD

**Issue by chihuy105** [leancodepl/patrol#2526]
### Steps to reproduce

Setup the patrol. And run the test

### Actual results

When run patrol test in android with a Emulator that don't have Google play service (android-34/default/arm64-v8a) in German language
The test going for awhile until it got the issue. It works on IOS side

<img width="822" alt="Image" src="https://github.com/user-attachments/assets/6967eb05-24f8-46ac-a9e8-3ce73d25cf46" />

### Logs

<details>
<summary>Logs</summary>

```
Unhandled exception:
FormatException: Missing extension byte (at offset 1188)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1950:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1609:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:777:19)
#9      _StreamController._add (dart:async/stream_controller.dart:651:7)
#10     _StreamController.add (dart:async/stream_controller.dart:606:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2455:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1609:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:777:19)
#16     _StreamController._add (dart:async/stream_controller.dart:651:7)
#17     _StreamController.add (dart:async/stream_controller.dart:606:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1942:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1385:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>

### Patrol version

  patrol: 3.14.0
  patrol_finders: 2.7.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.5.0
Flutter command: flutter 
  Flutter 3.27.1 • channel stable
Android: 
• Program adb found in /opt/homebrew/bin/adb
• Env var $ANDROID_HOME set to /Users/kyohuu/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Flutter (Channel stable, 3.27.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-VN)
    • Flutter version 3.27.1 on channel stable at /Users/kyohuu/fvm/versions/3.27.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (8 weeks ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

```

</details>

**Comment by chihuy105** [comment]
I found the same issue. Look like patrol not working with other language
https://github.com/leancodepl/patrol/issues/1334

**Comment by DmytroChuchmaiBarges** [comment]
@chihuy105 It seams this is caused by something else, I mean I often get the same error on en_US language. 
In my case "Missing extension byte (at offset 1066)", "Missing extension byte (at offset 1287)".

**Comment by Kendru98** [comment]
Hi, so repro steps are:
1. Have emulator like this:
 don't have Google play service (android-34/default/arm64-v8a) 
2. Set language to German on emulator
Correct?
- Additional question, this is something that is 100% reproducible or this is some random error that is flaky.

**Comment by chihuy105** [comment]
It happens on every run after 6 or 7 test. 
1. A emulator that don't have GG service
2. Yes

**Comment by Kendru98** [comment]
@chihuy105 Thanks for answer, last question, can you confirm that GG service has meaning here? If you have emulator with GG service and change language to german test pass?

**Comment by shovelmn12** [comment]
Same issue, locale is en_GB, have not tried to set to en_US:

```

FormatException: Missing extension byte (at offset 1484)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1959:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:310:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:306:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:70:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:115:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1778:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
#9      _StreamController._add (dart:async/stream_controller.dart:663:7)
#10     _StreamController.add (dart:async/stream_controller.dart:618:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2904:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1778:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
#16     _StreamController._add (dart:async/stream_controller.dart:663:7)
#17     _StreamController.add (dart:async/stream_controller.dart:618:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2323:31)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1646:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:128:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:195:5)


```

**Comment by kubicki-4human** [comment]
Same thing. Worked fine for some time.... Will try downgrading

**Comment by shovelmn12** [comment]
@kubicki-4human did it work?

@Kendru98 any news on a fix for this issue?

**Comment by Kendru98** [comment]
@shovelmn12 Hi, you also use an emulator without Google play service? There are some other priorities now, but I will forward this to team.

**Comment by shovelmn12** [comment]
@Kendru98 I am using an emulator with google play services ...

Anyways I am not using patrol anymore too many bugs and issues good luck to you :)

**Comment by chihuy105** [comment]
I’m not sure but this could be the problems
I have many test case and all of it start with a native webview login usung keycloak so I do a lot of native run at the start of each test using enterTextByIndex,… native method on the webview and alot of Future.delay

**Comment by DmytroChuchmaiBarges** [comment]
I am constantly having this error when running test in bulk i.e. without specifying a target and when I run the tests specifying the target, id does not fail. It is hard to debug though due to I need to wait about 10-20 tests to run until they fail, and the whole test process failing on this crash.

**Comment by kubicki-4human** [comment]
> [@kubicki-4human](https://github.com/kubicki-4human) did it work?
> 
> [@Kendru98](https://github.com/Kendru98) any news on a fix for this issue?

Downgrading didn't work, but just using another instance of emulator did. Weird..

**Comment by chihuy105** [comment]
what instance did you use?

**Comment by DmytroChuchmaiBarges** [comment]
It might be related to https://github.com/flutter/flutter/issues/81666

**Comment by chihuy105** [comment]
I think not on my case cause it’s Android

**Comment by DmytroChuchmaiBarges** [comment]
This is related to UTF8Devcoder.convertChunked which is used framework-wide.

**Comment by DmytroChuchmaiBarges** [comment]
hey there, I found a workaround for now:
When you run the test, you see **./gradlew :app:connectedStageDebugAndroidTest -Ptarget=/Users/path_to_your_code/integration_test/test_bundle.dart -Pdart-defines=....**
So, 
1. you do the patrol **build android** with all the params and targets
2. cd /android
3. run ./gradlew :app:connectedStageDebugAndroidTest -Ptarget=/Users/path_to_your_code/integration_test/test_bundle.dart -Pdart-defines=....

in this way it does not crash the patrol process.

**Comment by chihuy105** [comment]
Thanks let me check

**Comment by cljobs** [comment]
Same Issue .. Any updates?

**Comment by Kendru98** [comment]
> Same Issue .. Any updates?
Hi @cljobs, 
It is hard to reproduce for us, can you provide some cloned repo, and specific emulator config that problem exist? Also flutter --verbose logs etc?

**Comment by jBorkowska** [comment]
Hi @cljobs !
As @Kendru98 wrote, we couldn't reproduce this issue before, we need more information, To be more specific:
- a repo where we can reproduce this bug would be most useful
- logs from logcat - my guess for now is that the real error log is there

Also it would be very useful for us to know, why your tests failed at this moment (I know, that there is no error log related to your test, but at least tell us what action should be performed in test at the moment of crash)

**Comment by DmytroChuchmaiBarges** [comment]
[jBorkowska](https://github.com/jBorkowska) please have a look at workaround I described above, it seams that the issue is in Patrol CLI since if you run the test via gradle, i runs all fine. 
So somewhere in the process of running tests,I suppose there's some error happens during sending/receiving information between the patrol CLI and the app. btw, there's an open futter framework bug around this error.

**Comment by jBorkowska** [comment]
@DmytroChuchmaiBarges I read the thread, still we need the information I wrote about to debug it on our own

**Comment by cljobs** [comment]
I am experiencing this issue on all the Android devices I've tested. This includes a Samsung Galaxy S22, as well as Android 13 and 14 emulators, both with and without Google Play Services.

It's Logcat Error 

1. 'package:flutter_test/src/binding.dart': Failed assertion: line 1000 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.

2. dart:core-patch/errors_patch.dart 50:61        _AssertionError._doThrowNew
3. dart:core-patch/errors_patch.dart 40:5         _AssertionError._throwNew
4. package:flutter_test/src/binding.dart 1000:14  TestWidgetsFlutterBinding._runTest.handleUncaughtError
5. package:flutter_test/src/binding.dart 1005:9   TestWidgetsFlutterBinding._runTest.<fn>
6. dart:async/zone.dart 1081:14                   _Zone._processUncaughtError
7. dart:async/zone.dart 1285:5                    _CustomZone.handleUncaughtError
8. dart:async/future_impl.dart 811:16             Future._propagateToListeners
9. dart:async/future_impl.dart 674:5              Future._completeError


patrol: 3.14.1
patrol_cli: 3.5.1
androidx.test:orchestrator:1.5.1

**Comment by jBorkowska** [comment]
Thanks @cljobs . I'll try to reproduce this error.

If you're looking how to solve the error from logcat, check out this (from [setup instructions](https://patrol.leancode.co/documentation#setup)):

<img width="777" alt="Image" src="https://github.com/user-attachments/assets/0963f824-c755-4415-a43f-0c62ec8ddb6f" />

**Comment by cljobs** [comment]
I try do not modify `FlutterError.onError` but still error causes

It's Logcat Error


2025-04-09 10:15:16.648   606-745   ActivityManager         system_server                        I  Force stopping kr.co.teamblind.bleet.debug appid=10219 user=0: finished inst
2025-04-09 10:15:16.649   606-745   ActivityManager         system_server                        I  Killing 13357:kr.co.teamblind.bleet.debug/u0a219 (adj 0): stop kr.co.teamblind.bleet.debug due to finished inst
2025-04-09 10:15:16.651 13330-13330 app_process             app_process                          I  System.exit called, status: 0
2025-04-09 10:15:16.651 13330-13330 AndroidRuntime          app_process                          I  VM exiting with result code 0.
2025-04-09 10:15:16.652  8734-8734  BoundBrokerSvc          com.google.android.gms               D  onUnbind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
2025-04-09 10:15:16.653   606-745   ActivityTaskManager     system_server                        W  Force removing ActivityRecord{73a171a u0 kr.co.teamblind.bleet.debug/kr.co.teamblind.bleet.MainActivity} t2738 f}}: app died, no saved state
2025-04-09 10:15:16.654   877-1094  BtGatt.ScanManager      com.android.bluetooth                D  uid 10108 isForeground true scanMode -1
2025-04-09 10:15:16.655  8734-8734  BoundBrokerSvc          com.google.android.gms               D  onUnbind: Intent { act=com.google.android.gms.appset.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
2025-04-09 10:15:16.656   606-745   InputManager-JNI        system_server                        W  Input channel object '711e688 kr.co.teamblind.bleet.debug/kr.co.teamblind.bleet.MainActivity (client)' was disposed without first being removed with the input manager!





com....android.googlequicksearchbox  W  Failed to notify listeners
                                                                                                    java.util.concurrent.CancellationException
                                                                                                    	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
                                                                                                    	at com.google.common.util.concurrent.bv.get(PG:1)
                                                                                                    	at com.google.common.util.concurrent.ed.a(PG:1)
                                                                                                    	at com.google.common.util.concurrent.cj.r(PG:2)
                                                                                                    	at com.google.common.util.concurrent.cc.run(PG:4)
                                                                                                    	at com.google.common.util.concurrent.bg.execute(PG:1)
                                                                                                    	at com.google.common.util.concurrent.bj.c(PG:1)
                                                                                                    	at com.google.common.util.concurrent.bj.b(PG:3)
                                                                                                    	at com.google.common.util.concurrent.cy.done(PG:1)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
                                                                                                    	at java.util.concurrent.FutureTask.cancel(FutureTask.java:179)
                                                                                                    	at com.google.common.util.concurrent.bv.cancel(PG:1)
                                                                                                    	at com.google.android.apps.search.assistant.platform.ondevice.fulfillment.server.k.r.run(PG:1)
                                                                                                    	at com.google.apps.tiktok.tracing.eh.run(PG:2)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    	at com.google.common.util.concurrent.ea.a(PG:1)
                                                                                                    	at com.google.common.util.concurrent.cw.run(PG:4)
                                                                                                    	at com.google.common.util.concurrent.eb.run(PG:1)
                                                                                                    	at com.google.android.libraries.i.af.run(PG:1)
                                                                                                    	at com.google.android.libraries.i.an.run(PG:23)
                                                                                                    	at com.google.android.libraries.i.l.run(PG:2)
                                                                                                    	at com.google.android.libraries.i.q.run(PG:4)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)


java.lang.SecurityException: Caller androidx.test.services:10221 cannot post for pkg androidx.test.services in user 0
                                                                                                    	at com.android.server.notification.NotificationManagerService.resolveNotificationUid(NotificationManagerService.java:6851)
                                                                                                    	at com.android.server.notification.NotificationManagerService.cancelNotificationInternal(NotificationManagerService.java:6402)
                                                                                                    	at com.android.server.notification.NotificationManagerService$11.cancelNotification(NotificationManagerService.java:6300)
                                                                                                    	at com.android.server.am.ServiceRecord$3.run(ServiceRecord.java:1150)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:44)




(REDACTED) Failed to process cache entry for package(%s).
                                                                                                    android.content.pm.PackageManager$NameNotFoundException: androidx.test.services
                                                                                                    	at android.app.ApplicationPackageManager.getInstallSourceInfo(ApplicationPackageManager.java:2541)
                                                                                                    	at com.google.android.apps.gsa.nga.engine.ag.ae.a(PG:13)
                                                                                                    	at com.google.android.libraries.gsa.k.a.j.call(PG:2)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at com.google.common.util.concurrent.dq.run(PG:4)
                                                                                                    	at com.google.android.libraries.i.af.run(PG:1)
                                                                                                    	at com.google.android.libraries.i.an.run(PG:23)
                                                                                                    	at com.google.android.libraries.i.l.run(PG:2)
                                                                                                    	at com.google.android.libraries.i.q.run(PG:4)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by jBorkowska** [comment]
Could you post full log from the run? @cljobs

**Comment by jBorkowska** [comment]
Also I didn't reproduce the crash with getting this "FlutterError.onError override"

**Comment by cljobs** [comment]
I typed Command `patrol test --target integration_test/example_test.dart --flavor dev --device 'emulator-5554' --verbose`

<details>
<summary>Terminal Log</summary>

result:
```
Unhandled exception:
FormatException: Missing extension byte (at offset 1757)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1956:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#9      _StreamController._add (dart:async/stream_controller.dart:658:7)
#10     _StreamController.add (dart:async/stream_controller.dart:606:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2455:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#16     _StreamController._add (dart:async/stream_controller.dart:658:7)
#17     _StreamController.add (dart:async/stream_controller.dart:606:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1942:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1385:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
</details>

<details>
<summary>LogCat</summary>

```
2025-04-09 18:31:55.956  3566-3660  flutter                 kr.co.teamblind.bleet.debug          I  [ERROR] 2025-04-09 18:31:55.945768	0:00:00.000932	POST	/runDartTest
                                                                                                    'package:patrol/src/native/patrol_app_service.dart': Failed assertion: line 149 pos 12: '_testExecutionCompleted.isCompleted == false': is not true.
                                                                                                    dart:core                                                                 _AssertionError._throwNew
                                                                                                    package:patrol/src/native/patrol_app_service.dart 149:12                  PatrolAppService.runDartTest
                                                                                                    package:patrol/src/native/contracts/patrol_app_service_server.dart 27:28  PatrolAppServiceServer.handle
2025-04-09 18:31:55.964  3566-3648  PatrolServer            kr.co.teamblind.bleet.debug          E  PatrolJUnitRunner.runDartTest(example_test Bleet App Test): Invalid response 500, Internal Server Error
2025-04-09 18:31:55.966  3566-3648  TestRunner              kr.co.teamblind.bleet.debug          E  failed: runDartTest[example_test Bleet App Test](kr.co.teamblind.bleet.MainActivityTest)
2025-04-09 18:31:55.967  3566-3648  TestRunner              kr.co.teamblind.bleet.debug          E  ----- begin exception -----
2025-04-09 18:31:55.970  3566-3648  TestRunner              kr.co.teamblind.bleet.debug          E  java.lang.RuntimeException: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
                                                                                                    	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:153)
                                                                                                    	at kr.co.teamblind.bleet.MainActivityTest.runDartTest(MainActivityTest.java:32)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
                                                                                                    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                                                                    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
                                                                                                    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
                                                                                                    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2361)
                                                                                                    Caused by: pl.leancode.patrol.contracts.PatrolAppServiceClientException: Invalid response 500, Internal Server Error
                                                                                                    	at pl.leancode.patrol.contracts.PatrolAppServiceClient.performRequest(PatrolAppServiceClient.kt:47)
                                                                                                    	at pl.leancode.patrol.contracts.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:23)
                                                                                                    	at pl.leancode.patrol.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.kt:53)
                                                                                                    	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:145)
                                                                                                    	at kr.co.teamblind.bleet.MainActivityTest.runDartTest(MainActivityTest.java:32) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) 
                                                                                                    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
                                                                                                    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) 
                                                                                                    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) 
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) 
                                                                                                    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) 
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) 
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) 
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:128) 
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:27) 
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:128) 
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:27) 
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) 
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:115) 
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67) 
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58) 
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446) 
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2361) 
2025-04-09 18:31:55.970  3566-3648  TestRunner              kr.co.teamblind.bleet.debug          E  ----- end exception -----
2025-04-09 18:31:55.972  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  POST /configure started
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  Timeout: 10000 ms
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  Android UiAutomator configuration:
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  	waitForSelectorTimeout: 10000 ms
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  	waitForIdleTimeout: 5000 ms
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  	keyInjectionDelay: 50 ms
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  	actionAcknowledgmentTimeout: 3000 ms
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  	scrollAcknowledgmentTimeout: 200 ms
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  	toolType: 1
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  	uiAutomationFlags: 1
2025-04-09 18:31:55.973  3566-3611  PatrolServer            kr.co.teamblind.bleet.debug          I  POST /configure took 1 ms
2025-04-09 18:31:55.976  3566-3648  TestRunner              kr.co.teamblind.bleet.debug          I  finished: runDartTest[example_test Bleet App Test](kr.co.teamblind.bleet.MainActivityTest)
2025-04-09 18:31:55.979  3566-3648  TestRunner              kr.co.teamblind.bleet.debug          I  run finished: 2 tests, 1 failed, 0 ignored
```
</details>

**Comment by jBorkowska** [comment]
> internal Server Error maybe https://github.com/leancodepl/patrol/issues/2268

From looking at your command I can tell that you don't run the same test twice, so it's not that one

The log you posted is not full logcat log from the test execution, only a part with an error. Unfortunately it's not enough information to know why it crashed. Please post whole log or provide a repository where I can reproduce the error (doesn't have to be your project, even better if it's just a sample project where this error occurs)

**Comment by jBorkowska** [comment]
@pdenert I think it's related to logs feature, we fixed similar one already but this is not the same (with too long logs bc of a native error)

**Comment by cljobs** [comment]
maybe I found it..!

my project use Logger Package to Log Http Call.
I turn off Http Intercept, It succeed

**Comment by jpoh281** [comment]
This is my personal account.

During testing, I confirmed that this error occurs when trying to print the response body using the `_printAll` message within this section of the code: https://github.com/cfug/dio/blob/808f81b5920e0df3173ce836da340629385722f4/dio/lib/src/interceptors/log.dart#L121-L146

However, although I tried creating an example project, I couldn't determine the exact text that triggers the error exposure.

Is it possible to fix the problem where the CLI encounters issues when specific strings are received by modifying the patrol_cli library?

**Comment by GChanathip** [comment]
I got this issue when use Patrol 3.13.0 and Patrol_cli 3.4.0.
not sure why it happen with Andorid only.

**Comment by GChanathip** [comment]
In my case, The issue is gone after i upgrade flutter version from 3.24.4 to 3.29.3 and above.
I also update all patrol dependency to latest version.

edited: now the issue is back to me 🤷‍♂️

**Comment by andriiShutov** [comment]
After update Android studio with all plugins (emulator, android sdk, etc) this issue stopped reproducing. Theoretically - this was fixed in the new Android SDK

**Comment by kkabanova** [comment]
> After update Android studio with all plugins (emulator, android sdk, etc) this issue stopped reproducing. Theoretically - this was fixed in the new Android SDK

@andriiShutov could you share android sdk version that you're using? and flutter/patrol version please

ty in advance

**Comment by andriiShutov** [comment]
@kkabanova 
Patrol:
Patrol CLI version: 3.6.0
patrol_finders: 2.7.2
patrol: 3.15.1

Flutter:
Flutter (Channel stable, 3.29.3, on macOS 15.0 24A335 darwin-arm64 (Rosetta), locale en-UA)
 Android toolchain - develop for Android devices (Android SDK version 34.0.0)

SDK Tools:
<img width="977" alt="Image" src="https://github.com/user-attachments/assets/b8295749-9ef7-4b00-a9e3-74d2963735d9" />

**Comment by rolandmosimann** [comment]
I still get this with the same config, but running it on a physical Pixel 8:
Patrol:
Patrol CLI version: 3.6.0
patrol_finders: 2.7.2
patrol: 3.15.1
Flutter: Channel stable, 3.29.3
Android 14 (=SDK 34)

**Comment by ivan-horchakov** [comment]
I'm getting it too from time to time ("Unhandled exception:
FormatException: Missing extension byte (at offset 1066)") and in my case it isn't related to other languages. It happens right before exception in test should appear. I saw [this post](https://github.com/leancodepl/patrol/discussions/2455) in Patrol's discussion and it says that this kind of exceptions started to appear right after Patrol added emojis in terminal output.

**Comment by andriiShutov** [comment]
This issue returned to me again. Any fixes?

**Comment by Kendru98** [comment]
I think we're still waiting for steps to reproduce it. It looks like this is flaky. We are not able to reproduce this.

**Comment by mmatook** [comment]
Same issue here after upgrading to patrol_cli v3.9.0 and patrol:3.18.0. 
No issues before upgrading.

`      ✅  18. tap widgets with text "Next".
        ✅  19. tap widgets with text "Next".
        ⏳  20. tap widgets with text "Lets get started".
Unhandled exception:
FormatException: Missing extension byte (at offset 1066)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1959:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:310:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:306:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:70:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:115:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1778:10)`

**Comment by Noxiver** [comment]
Hi everyone. This fix (steps) solved it for me and might help you as well
https://github.com/leancodepl/patrol/discussions/2455#discussioncomment-14435895

**Comment by TakeshiYonezawa** [comment]
I was able to prevent the crash by making the UTF-8 decoder lenient.

**Repro**
When logcat outputs a very long line containing multibyte characters, 
`patrol_cli` crashes with:

FormatException: Missing extension byte (at offset XXXX)

**Patch**
In `packages/patrol_cli/lib/src/base/process.dart`,   
`extension ProcessListeners` (both `listenStdOut` and `listenStdErr`),

I changed:

```dart
.transform(utf8.decoder)
```

to

```dart
.transform(const Utf8Decoder(allowMalformed: true))
```

**Result**

Crash no longer occurs.

Maybe Patrol CLI could adopt a similar approach or implement line buffering to avoid
crashing when logcat chunks split UTF-8 sequences.

**Comment by andriiShutov** [comment]
I can confirm that @TakeshiYonezawa  fix worked for me.
I deleted my previous post. Before that I wrote that it didn't work because I made a mistake.
For those who need it - you need to git clone the patrol_cli package, make the necessary changes and then activate it like this: dart pub global activate --source path .

**Comment by Noxiver** [comment]
@Kendru98 take a look pls

**Comment by Kendru98** [comment]
Good job guys, especially @TakeshiYonezawa,  did you observe any regressions in cli or patrol logs after this change? If you want (you should be able to) create a PR for this fix 🙏. If not, just tell me I can do it, but I don't want to take your credits :D

**Comment by TakeshiYonezawa** [comment]
@Kendru98 
Thanks! After this change the crash is gone, but I haven't verified how it affects the logs in all cases.

Because I don't know yet what the side effects might be, I'd prefer not to open a PR myself. 
I think it would be better if maintainers decide whether to apply this approach by default (or maybe behind a flag) and check that it doesn't break log parsing.

Please feel free to take over and implement it properly if you think it's the right fix 🙏

**Comment by andriiShutov** [comment]
Thank you very much for the fix @TakeshiYonezawa ! Now I can run 200+ tests in run without fear that it will stop after random case.

**Comment by Kendru98** [comment]
Will do it hopefully tomorrow, thanks guys once again. Have a nice weekend :D

**Comment by Kendru98** [comment]
Released in cli 3.11 and patrol 3.20
